Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,10 +23,35 @@ jobs:
       - name: Build with Maven
         run: mvn -B clean install --file pom.xml
 
-      - name: List files
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/surefire-reports/TEST-*.xml'
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Jacoco Report to PR
+        id: jacoco
+        uses: madrapps/jacoco-report@v1.6.1
+        with:
+          paths: ${{ github.workspace }}/**/target/site/jacoco/**/jacoco.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          min-coverage-overall: 40
+          min-coverage-changed-files: 60
+          title: Code Coverage
+          update-comment: true
+
+      - name: Fail PR if overall coverage is less than 40%
+        if: ${{ steps.jacoco.outputs.coverage-overall < 40.0 }}
+        uses: actions/github-script@v6
+        with:
+          script: |
+            core.setFailed('Overall coverage is less than 40%!')
+
+      - name: Log coverage percentage
         run: |
-          echo "List of files in workspace:"
-          ls -R .
+          echo "coverage-all = ${{ steps.jacoco.outputs.coverage-overall }}"
+          echo "coverage-changed-files = ${{ steps.jacoco.outputs.coverage-changed-files }}"
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
